width = 240
height = 180
lr = 2e-4
sequence_len = 30
color_channels = 3
output_classes = 7
eps = 5
BATCH_SIZE = 32
fps_at_recording_time = 80      # check by using main with fps only set to true, while having the game running
fps_at_test_time = 8    # check by running model in main
data_dir_name = "data/"
model_dir_name = "models/"
cnn_only_name = model_dir_name + "car_inception_only_4"
model_name = model_dir_name + "car_inception_pretrained_lstm_v1_cc_epoch_2"
load_data_name = data_dir_name + "training_data_for_lstm_rgb_full.npy"
temp_data_chunk_name = "temp_dataset_chunk_"
temp_data_folder_name = "data_in_chunks_temp"
new_data_dir_name = data_dir_name + "new_data/"
data_name = f"{width}x{height}_rgb"
old_data_name = "training_data_rgb_part"
